-- 1. Create the Gallery Table if it doesn't exist
create table if not exists public.gallery (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_url text not null,
  caption text
);

-- 2. Enable Row Level Security (RLS)
alter table public.gallery enable row level security;

-- 3. Create Policies for the Gallery Table (Drop first to avoid errors if they exist)

drop policy if exists "Enable read access for all users" on public.gallery;
create policy "Enable read access for all users" on public.gallery for select to public using (true);

drop policy if exists "Enable insert for authenticated users only" on public.gallery;
create policy "Enable insert for authenticated users only" on public.gallery for insert to authenticated with check (true);

drop policy if exists "Enable delete for authenticated users only" on public.gallery;
create policy "Enable delete for authenticated users only" on public.gallery for delete to authenticated using (true);


-- 4. CREATE STORAGE BUCKET (Automatically via SQL)
insert into storage.buckets (id, name, public)
values ('gallery-images', 'gallery-images', true)
on conflict (id) do nothing; -- Skip if already exists


-- 5. Storage Policies
-- Drop existing policies first to avoid conflicts
drop policy if exists "Give public access to gallery images" on storage.objects;
drop policy if exists "Allow authenticated uploads" on storage.objects;
drop policy if exists "Allow authenticated delete" on storage.objects;

-- Create policies
create policy "Give public access to gallery images"
on storage.objects for select
to public
using ( bucket_id = 'gallery-images' );

create policy "Allow authenticated uploads"
on storage.objects for insert
to authenticated
with check ( bucket_id = 'gallery-images' );

create policy "Allow authenticated delete"
on storage.objects for delete
to authenticated
using ( bucket_id = 'gallery-images' );
